### PR TITLE
Adding a "Welcome to Haskell" demo notebook

### PR DESCRIPTION
**Pull request by gibiansky**
Includes an intro to the Jupyter interface, a few Haskell code snippets, and links to other materials.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Rad. Thanks!

**Comment by gibiansky** [comment]
Awesome! What's a rough ETA for when this notebook will show up on try.jupyter.org? I'd like to show it to the greater Haskell community and ask for input on the code snippets. (I dunno if that's an automatic update, someone has to restart the server, or what, etc)

**Comment by Carreau** [comment]
Usually Kyle rebuilds on week-end. See [here](https://github.com/jupyter/docker-demo-images/pull/45#issuecomment-105457524) for more info.

**Comment by rgbkrk** [comment]
Build is pretty easy. It's the cycling out of old users that takes time.

**Comment by rgbkrk** [comment]
*old containers

**Pull request merged**
