### PR TITLE
IHaskell widgets

### PR DESCRIPTION
**Pull request by sumitsahrawat**
- Install `ihaskell-widgets` package
- Install dependencies for the examples
- Copy examples to `featured/`
- Upgrade IHaskell version as required

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
Hi @rgbkrk.

I haven't tried building this, because I nuked the virtual machine I used to build docker-demo-images earlier. The image has gotten quite large now and starting from scratch would take a lot of time.

The size difference should not be that large, as almost all of the dependencies of the new components are already installed indirectly as dependencies of IHaskell.

**Comment by sumitsahrawat** [comment]
@rgbkrk The PR won't work until @gibiansky uploads `ihaskell-widgets` to hackage.

**Comment by rgbkrk** [comment]
Ok, good to know. Thanks for the addition!

**Comment by gibiansky** [comment]
@rgbkrk @sumitsahrawat `ihaskell-widgets` has been uploaded.

**Comment by rgbkrk** [comment]
:boom:

**Comment by gibiansky** [comment]
Any updates on when this will be on `try.jupyter.org`? We'd love to use this to show off @sumitsahrawat's  Google Summer of Code to the Haskell community!

**Comment by rgbkrk** [comment]
As soon as we have Jupyter 4.0 migrated over (or if our base image is pinned), we'll deploy again. Last time I deployed it was an old image just to make sure capacity was fine.

**Comment by sumitsahrawat** [comment]
Great, got my eyes peeled :+1: :smile:

**Pull request merged**
