### PR TITLE
Add a header button for current sponsor, Rackspace

### PR DESCRIPTION
**Pull request by rgbkrk**
This is an attempt for #24, to add a Rackspace logo to the current demo setup.

Current Prototype:

screenshot 2015-05-07 22 43 09

screenshot 2015-05-07 22 45 14

/cc @fperez @ellisonbg

### CODE REVIEW

**Comment by rgbkrk** [comment]
Updated the mockups. Maybe that's a bit too flashy.

**Comment by rgbkrk** [comment]
Alternative with just the little logo person:

screenshot 2015-05-07 22 51 52

Perhaps the wording prior can be "running on", "hosted by" or something similar?

**Comment by rgbkrk** [comment]
Final draft of the night with text. This checks for `notebook_name` in jinja to determine what text comes before the logo.

Dashboard page:

screenshot 2015-05-07 23 15 32

Notebook page:

screenshot 2015-05-07 23 16 04

**Comment by ellisonbg** [comment]
Do you think that the Rackspace logo is well known enough that people will
know what it is? I like the design though.

On Thu, May 7, 2015 at 9:17 PM, Kyle Kelley <notifications@github.com>
wrote:

> Final draft of the night with text. This checks for notebook_name in
> jinja to determine what text comes before the logo.
>
> Dashboard page:
>
> [image: screenshot 2015-05-07 23 15 32]
> <https://cloud.githubusercontent.com/assets/836375/7530496/222f39e4-f50f-11e4-991e-15ff893de9fd.png>
>
> Notebook page:
>
> [image: screenshot 2015-05-07 23 16 04]
> <https://cloud.githubusercontent.com/assets/836375/7530501/32a9dbe4-f50f-11e4-8d8b-423eccbc9e22.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-demo-images/pull/36#issuecomment-100097186>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
> Do you think that the Rackspace logo is well known enough that people will
know what it is?

Gosh Brian, don't make me loop in Marketing.

I agree that it should probably say Rackspace, but I also like it fairly minimal. One of the qualms @jdfreder had was that the font in the Rackspace logo was a bit heavy for the notebook.

**Comment by ellisonbg** [comment]
What about puting "Rackspace" as text rather than logo...

On Thu, May 7, 2015 at 9:21 PM, Kyle Kelley <notifications@github.com>
wrote:

> Do you think that the Rackspace logo is well known enough that people will
> know what it is?
>
> Gosh Brian, don't make me loop in Marketing.
>
> I agree that it should probably say Rackspace, but I also like it fairly
> minimal. One of the qualms @jdfreder <https://github.com/jdfreder> had
> was that the font in the Rackspace logo was a bit heavy for the notebook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-demo-images/pull/36#issuecomment-100097430>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
Totally fine by me.

**Comment by rgbkrk** [comment]
screenshot 2015-05-07 23 25 43

Blech. Perhaps in a footer instead if text?

**Comment by ellisonbg** [comment]
Yeah, blah. What about "Rackspace" in text, but with the logo ?

On Thu, May 7, 2015 at 9:25 PM, Kyle Kelley <notifications@github.com>
wrote:

> [image: screenshot 2015-05-07 23 25 43]
> <https://cloud.githubusercontent.com/assets/836375/7530555/5a1a0a54-f510-11e4-9b23-8d8c02dd8900.png>
>
> Blech. Perhaps in a footer instead if text?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-demo-images/pull/36#issuecomment-100097693>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
screenshot 2015-05-07 23 53 11

**Comment by ellisonbg** [comment]
I like that!

On Thu, May 7, 2015 at 9:53 PM, Kyle Kelley <notifications@github.com>
wrote:

> [image: screenshot 2015-05-07 23 53 11]
> <https://cloud.githubusercontent.com/assets/836375/7530765/2fbc1b72-f514-11e4-9457-128221908d4e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-demo-images/pull/36#issuecomment-100100073>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
Mmh, silly comment: 'Hosted' instead of 'hosted'?  I'm kind of old-school when it comes to grammar and punctuation, so perhaps you should ignore me :)

**Comment by jhamrick** [comment]
I like it too! And I agree with @fperez , I also think it should be "Hosted" instead of "hosted" :)

**Comment by rgbkrk** [comment]
Normally I'm one to nitpick about grammar and punctuation, that's totally fine. :wink: You got me.

screenshot 2015-05-08 00 43 13

**Comment by fperez** [comment]
me liKE iT. thANK yOu!

**Comment by rgbkrk** [comment]
At FiRst I thougHt you HAD a keyborad mishap, then I realized what we were talking about.

**Comment by rgbkrk** [comment]
I'm going to merge this and ship it now that try.jupyter.org is bearing the load of jupyter.org links. :wink:

screenshot 2015-05-08 10 53 23

**Comment by rgbkrk** [comment]
Bit of an oversight - the Rackspace logo is not served over HTTPS which leaves us in a mixed contents state. I'll have to find another (or host it ourselves) but it's not a pressing issue.

Also want to state that if anyone is unhappy with this placement, I'm open to other options. Thanks all.

**Comment by jdfreder** [comment]
The end result looks good :+1:

**Comment by fperez** [comment]
Great, thanks @rgbkrk!

**Pull request merged**
