### PR TITLE
Added the notebook which introduces usage of Apache Spark in Scala, i…

### PR DESCRIPTION
**Pull request by guiwork**
Added a notebook which uses the Apache Spark Scala API. It mimics the notebook created in Python by @parente

### CODE REVIEW

**Comment by guiwork** [comment]
Resolves issue #79

**Comment by parente** [comment]
Thanks @guiwork. The `notebooks` dir winds up right into the root of the image. Can you update the `"../datasets/COUNT/titanic.csv"` path to `"datasets/COUNT/titanic.csv"` so that it works out of the box?

**Comment by rgbkrk** [comment]
If this gets in soon, let's ship this along with the other changes.

**Comment by guiwork** [comment]
All done with that change @parente and @rgbkrk

**Comment by parente** [comment]
I tried drag/dropping it into tmpnb.org and it LGTM.

**Comment by rgbkrk** [comment]
:boom: thanks

**Pull request merged**
