### PR TITLE
Bring in R datasets.

### PR DESCRIPTION
**Pull request by rgbkrk**
This brings in the R datasets for use in our demo, so they can be used across languages.

### CODE REVIEW

**Comment by Carreau** [comment]
Weird, a PR from kyle which is not immediately merged...

**Comment by rgbkrk** [comment]
This brings in about 13.7 MB into the repo (and resulting Docker container) but hey our image is kind of huge anyway.

**Comment by rgbkrk** [comment]
Are you saying I'm wrapping stuff up on docker-demo-images too quickly and you want to be more involved? I'm happy to oblige there.

**Comment by Carreau** [comment]
No, I'm just joking, you are doing a pretty awesome job. I'm at the limit of the things I can handle. 
(I saw jupyter-path BTW)

**Comment by rgbkrk** [comment]
> I saw jupyter-path BTW

Yeah, it's roughly the same as the one I contributed to Hydrogen. I'll be using it in sidecar (or any other Electron/Atom apps).

**Pull request merged**
