### PR TITLE
Add pandas cookbook to featured notebooks

### PR DESCRIPTION
**Pull request by jvns**
I hope this is right! I cargo culted from what was in the Dockerfile already.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Ship it

**Comment by rgbkrk** [comment]
Thanks @jvns!

**Comment by rgbkrk** [comment]
Expect about a half day before this is up and ready to be consumed. ;)

**Comment by jvns** [comment]
Yay! Thanks so much :D

**Comment by rgbkrk** [comment]
All set. They're online!

It would be super cool if you upgrade your notebooks to v4, otherwise they're going to have a warning:

screenshot 2015-02-11 15 34 12

Easy mode is running

```
find . -name '*.ipynb' -exec ipython nbconvert --to notebook {} --output {} \;
```

I can add that to our build process, but it would be good to make sure it works against your collection of notebooks.

**Comment by rgbkrk** [comment]
Urp, forgot to say you'll need the latest release of 2.4.1 or the coming IPython 3 release `pip install --pre ipython[all]`.

**Pull request merged**
