### PR TITLE
Add datasets require for spark ebook project

### PR DESCRIPTION
**Pull request by odewahn**
This PR adds a few datasets for an interactive ebook project about Spark from MAPR and O'Reilly Media.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Works for me! We'll need to make sure these get included in the refactored version of this image in #71.

**Comment by odewahn** [comment]
This is great!  Thanks @rgbkrk!  Any insight on when will these show up on the tmpnb containers?

**Comment by rgbkrk** [comment]
If we don't get #71 merged and in a happy state soon, I'll push the current version of the images out soon enough.

**Comment by odewahn** [comment]
Great!  My only concern is that we're trying to get this out for Strata next week (the 29th of September) and we need a few days to test it.

**Comment by parente** [comment]
I was planning on getting tini into jupyter/minimal-notebook tonight. After that, we might be able to merge #71 but we need to take an accounting of what else needs to be resolved there first for redeploy.

@rgrkrk do you have a staging area in which to test new tmpnb.org deploys before they go live?

**Comment by rgbkrk** [comment]
I launch new servers

**Comment by rgbkrk** [comment]
I accidentally commented before finalizing my comment. :stuck_out_tongue_closed_eyes: Don't hit shift-enter.

Every time I deploy, it tends to be a fresh deploy with a clean slate. Sometimes I just update the image on the server, but in the case of this one I'd do a brand new one.

**Comment by rgbkrk** [comment]
The reason why I do new machines is because we

* wait to migrate people off of old nodes
* assume they're all compromised wastelands of containers

**Pull request merged**
