### PR TITLE
use sciruby-full

### PR DESCRIPTION
**Pull request by minad**
Based on https://github.com/SciRuby/sciruby-notebooks/blob/master/Dockerfile. This install all the interesting libraries from the sciruby-project, including nyaplot etc.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome!

Out of curiosity, can the sciruby stack be built with OpenBLAS instead of Atlas? IIRC, OpenBLAS tends to be faster and only one of them can be installed on the system. We're using conda so it won't affect python+R but it will affect Julia (or so I think).

**Comment by rgbkrk** [comment]
Relatedly, nyaplot won't work on try jupyter until https://github.com/domitry/nyaplot/pull/40 is merged and shipped. All assets need to be loaded over HTTPS.

**Comment by minad** [comment]
@rgbkrk Yes, but the nyaplot issue has nothing to do with this pull request. sciruby-full will automatically pull in the new nyaplot version if it is released.

**Comment by rgbkrk** [comment]
Alright, sounds good. Thanks for answering about OpenBLAS.

**Comment by minad** [comment]
thx

**Comment by rgbkrk** [comment]
Just tried to make the build here and it looks like its missing something?

```
Building native extensions.  This could take a while...
ERROR:  Error installing sciruby-full:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
checking for gcc... yes
checking for Magick-config... no
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.4.9)... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
extconf.rb:79:in ``': No such file or directory - convert (Errno::ENOENT)
	from extconf.rb:79:in `block in configure_compile_options'
	from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
	from extconf.rb:76:in `configure_compile_options'
	from extconf.rb:15:in `initialize'
	from extconf.rb:474:in `new'
	from extconf.rb:474:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/rmagick-2.15.2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/rmagick-2.15.2/gem_make.out
INFO[0407] The command [/bin/sh -c gem install --no-rdoc --no-ri sciruby-full] returned a non-zero code: 1
make: *** [demo-image] Error 1
```

Does it need `libmagick`?

```
root@2468a129832f:~# apt-cache search libmagic
libmagic-dev - File type determination library using "magic" numbers (development)
libmagic1 - File type determination library using "magic" numbers
graphicsmagick-libmagick-dev-compat - image processing libraries providing ImageMagick interface
libmagick++-6-headers - object-oriented C++ interface to ImageMagick - header files
libmagick++-6.q16-5 - object-oriented C++ interface to ImageMagick
libmagick++-6.q16-dev - object-oriented C++ interface to ImageMagick - development files
libmagick++-dev - object-oriented C++ interface to ImageMagick
libmagickcore-6-arch-config - low-level image manipulation library - architecture header files
libmagickcore-6-headers - low-level image manipulation library - header files
libmagickcore-6.q16-2 - low-level image manipulation library -- quantum depth Q16
libmagickcore-6.q16-2-extra - low-level image manipulation library - extra codecs (Q16)
libmagickcore-6.q16-dev - low-level image manipulation library - development files (Q16)
libmagickcore-dev - low-level image manipulation library -- transition package
libmagickwand-6-headers - image manipulation library - headers files
libmagickwand-6.q16-2 - image manipulation library
libmagickwand-6.q16-dev - image manipulation library - development files
libmagickwand-dev - image manipulation library - transition for development files
libfile-libmagic-perl - Perl interface to libmagic for determining file type
libmagics++-data - Data files needed for magics++ library
libmagics++-dev - Development files for ECMWF  plotting software MAGICS++
libmagics++-metview-dev - Libraries needed for building MetView
libmagic-ocaml - OCaml bindings for the File type determination library
libmagic-ocaml-dev - OCaml bindings for the File type determination library
ruby-magic - Ruby FFI bindings to libmagic
```

**Comment by minad** [comment]
Sorry, I think it is  libmagickwand-dev

**Comment by rgbkrk** [comment]
`apt-get install libmagickwand*` wasn't even enough.

**Comment by rgbkrk** [comment]
However, `apt-get install imagemagick libmagick++-dev` did the trick (parallel builds with different dependencies for the win).

**Comment by minad** [comment]
that's weird. I don't have that in https://github.com/SciRuby/sciruby-notebooks/blob/master/Dockerfile

**Pull request merged**
