### PR TITLE
add iruby kernel

### PR DESCRIPTION
**Pull request by minad**
IRuby 0.2.0 works with jupyter. Would be great if you add it :)

### CODE REVIEW

**Comment by rgbkrk** [comment]
Sweet, this looks very clean. Thanks @minad.

**Comment by rgbkrk** [comment]
Also, I'd totally be happy if nyaplot was installed.

**Comment by rgbkrk** [comment]
This appears to have propagated across https://try.jupyter.org

:+1:

**Comment by minad** [comment]
thx, thats great :)

**Comment by minad** [comment]
How often does this propagation happen if I create a new release? We will include nyaplot and other niceties at some point. I will create a pull request then. But these are under heavy development right now.

**Comment by rgbkrk** [comment]
Takes a few hours after we merge a PR on here, mostly because old images get cycled out.

As for how often a new image goes out, that's up to one of us finding that there are updates. Pretty soon the R kernel will get updates in conda and I'll ship again.

**Comment by minad** [comment]
I wonder about the docker caching if the command doesn't change but an updates happen. What about regenerating the whole image in a daily or weekly cycle?

**Comment by rgbkrk** [comment]
Typically I'll regenerate the whole image from scratch when I know about changes at the base or generally on a weekly basis (on the weekend). We used to build from Docker Hub but ran into strange non-deterministic user permission issues.

**Comment by minad** [comment]
great thx

**Pull request merged**
